/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.google.code.gson:gson:2.8.6")
    implementation("org.apache.commons:commons-collections4:[4.1,)")
    implementation("org.projectlombok:lombok:1.18.12")
    implementation("com.fasterxml.jackson.core:jackson-core:2.11.1")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.11.1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.11.1")
    implementation("com.google.protobuf:protobuf-java:3.2.0")
    implementation("com.google.protobuf:protobuf-java-util:3.2.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.4.2")
}

group = "core-java-learning"
version = "1.0-SNAPSHOT"
description = "samples"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
