/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */


import com.google.protobuf.gradle.*

plugins {
    id("java")
    id("maven-publish")
    id("com.google.protobuf") version "0.8.19"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.google.code.gson:gson:2.9.0")
    implementation("org.apache.commons:commons-collections4:4.4")
    implementation("org.projectlombok:lombok:1.18.24")
    implementation("com.fasterxml.jackson.core:jackson-core:2.13.4")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.13.4")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.4")
    implementation("com.google.protobuf:protobuf-java:3.21.5")
    implementation("com.google.protobuf:protobuf-java-util:3.21.5")
    implementation("io.grpc:grpc-stub:1.49.0")
    implementation("io.grpc:grpc-protobuf:1.49.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.0")

    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    testCompileOnly("org.projectlombok:lombok:1.18.24")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.24")

    protobuf(files("src/main/protobuf"))
    testProtobuf(files("src/main/protobuf"))
}

group = "core-java-learning"
version = "1.0-SNAPSHOT"
description = "samples"
java.sourceCompatibility = JavaVersion.VERSION_11

protobuf {
    protoc {
        // The artifact spec for the Protobuf Compiler
        artifact = "com.google.protobuf:protoc:3.10.0"
    }
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}